name: "Release"
on:   
  workflow_dispatch:
    inputs:
      targetRepo: 
        description: 'Environment (dev, stage, prod)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: 'master'
    - name: Keep dist up-to-date
      run: |
        npm i
        npm run build
        npm run pack
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "chore: publish dist" || echo "nothing to commit"
        git push origin master
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Test Action
      uses: ./
      with: 
        SECRETS: |
          ^FOO$
          ^GITHUB_.*
        REPOSITORIES: |
          ^jvsrikanth11/scrs-test-secrets-project$
        DRY_RUN: true
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      env:
        FOO: ${{github.run_id}}
        FOOBAR: BAZ
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master 
