name: "Release"
on:   
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Environment (dev, stage, prod)'
        default: dev
        required: true
      repository:
        description: 'Repository (scrs-*)'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: 'master'
    - name: Keep dist up-to-date
      run: |
        npm i
        npm run build
        npm run pack
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "chore: publish dist" || echo "nothing to commit"
        git push origin master
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    
    - name: Push repo secrets
      uses: ./
      with: 
        SECRETS: |
          ^APP_KEY$
        REPOSITORIES: |
          ^jvsrikanth11/${{ github.event.inputs.repository }}$
        DRY_RUN: false
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        
    - name: Push environment secrets
      if: ${{ github.event.inputs.environment != '' }}
      uses: ./
      with: 
        SECRETS: |
          ^COSMOS_.*
        REPOSITORIES: |
          ^jvsrikanth11/${{ github.event.inputs.repository }}$
        DRY_RUN: false
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        ENVIRONMENT: ${{ github.event.inputs.environment }}
      env:
        COSMOS_DB: ${{ secrets.COSMOS_DB }}
