name: "Release"
on:   
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Environment (dev, stage, prod)'
        default: dev
        required: true
      repository:
        description: 'Define repository (scrs-*)'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: 'master'
    - name: Keep dist up-to-date
      run: |
        npm i
        npm run build
        npm run pack
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "chore: publish dist" || echo "nothing to commit"
        git push origin master
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Test Action
      uses: ./
      with: 
        SECRETS: |
          ^COSMOS_.*
        REPOSITORIES: |
          ^jvsrikanth11/${{ github.event.inputs.repository }}$
        DRY_RUN: false
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        ENVIRONMENT: ${{ github.event.inputs.environment }}
      env:
        COSMOS_DB_${{ github.event.inputs.environment }}: ${{ secrets.COSMOS_DB_${{ github.event.inputs.environment }}}}
